#ifndef EXTI_CONFIG_H_
#define EXTI_CONFIG_H_

/* EXTI LINES :	1- EXTI_LINE0
				2- EXTI_LINE1 
				3- EXTI_LINE2 
*/
#define EXTI_LINE 		EXTI_LINE0

/* EXTI Snese Mode :	1- EXTI_RISING_EDGE
						2- EXTI_FALLINF_EDGE
						3- EXTI_ON_CHANGE
						4- EXTI_LOW_LEVEL
*/

#define EXTI_SENSE 			EXTI_RISING_EDGE


#endif