/*
 * TIMER0_config.h
 *
 *  Created on: Aug 12, 2021
 *      Author: ibrahim
 */

#ifndef MCAL_TIMER0_TIMER0_CONFIG_H_
#define MCAL_TIMER0_TIMER0_CONFIG_H_
/*
 * NORMAL , COMPARE_MATCH
 */

#define TIMER0_MODE_OPERATION	COMPARE_MATCH
/*
 * DISABLE , ENABLE
 */
//#define TIMER0_OVERFLOW_INTERRUPT	ENABLE

/*
 * DISABLE , ENABLE
 */
#ifndef TIMER0_OVERFLOW_INTERRUPT
#define TIMER0_COMPARE_MATCH_INTERRUPT	ENABLE
#endif

/*
 * ENABLE
 * DISABLE
 */

#define TIMER0_ENABLE_DISABLE	ENABLE
/*
 * TIM0_CLK
 * TIM0_CLK_8
 * TIM0_CLK_64
 * TIM0_CLK_256
 * TIM0_CLK_1024
 */
#define TIMER0_CLK_PRESCALLER	TIM0_CLK_64


#endif /* MCAL_TIMER0_TIMER0_CONFIG_H_ */
